Fix Issue 28
ohmzeus/Cooler pull request #48
Opened 2023-09-05 00:44 UTC by ohmzeus

Summary: Can steal gOhm by calling Clearinghouse.claimDefaulted on loans not made by Clearinghouse
Issue Link: https://github.com/sherlock-audit/2023-08-cooler-judging/issues/28
Fix Description: Validate that a defaulted loan was written by the clearinghouse before incentivizing it.

2023-09-05 11:13 UTC, ind-igo requested changes

2023-09-05 11:19 UTC, ind-igo commented on src/Clearinghouse.sol
> +            if (Cooler(coolers_[i]).getLoan(loans_[i]).lender != address(this)) continue;
There should also be a test created to verify this is working as intended.

2023-09-05 21:21 UTC, ohmzeus commented on src/Clearinghouse.sol
> +            if (Cooler(coolers_[i]).getLoan(loans_[i]).lender != address(this)) continue;
> Ser this needs to revert here, not continue

Should be able to just move onto the next index in the array's, no? I don't think it needs to revert the whole tx as long as it ignores invalid loans. At the end of the day both work though; revert just requires caller has properly vetted the list.

2023-09-07 08:01 UTC, 0xRusowsky commented on src/Clearinghouse.sol
> +            if (Cooler(coolers_[i]).getLoan(loans_[i]).lender != address(this)) continue;
Agreed to revert.

There is no point in covering cases that don't apply to us. If the keeper is sending loans that the CH did not create, it is fair to assume that there is malicious intent.

2023-09-07 17:21 UTC, 0xRusowsky commented
ready for merge

2023-09-11 22:33 UTC, merged