fix: issue 176 - MINTR missing OHM approval
ohmzeus/Cooler pull request #52
Opened 2023-09-07 23:27 UTC by 0xRusowsky

Summary: Clearinghouse.sol#claimDefaulted() - Clearinghouse doesn't approve the MINTR to handle tokens in his name, which bricks the entire function.
Issue Link: https://github.com/sherlock-audit/2023-08-cooler-judging/issues/176
Fix Description: Give `MINTR` infinite approval on the OHM token inside the configureDependencies function.

2023-09-08 08:11 UTC, ind-igo commented on src/Clearinghouse.sol
> +        ohm = ERC20(ohm_);
You can grab the OHM address by calling IStaking(staking_).OHM();

I would move this line below line 91, after initializing staking

2023-09-08 08:15 UTC, ind-igo requested changes

2023-09-08 08:15 UTC, ind-igo commented on src/Clearinghouse.sol
> +        ohm.safeApprove(address(MINTR), type(uint256).max);
If you are using safeApprove here, you may as well use it everywhere. If not, you can just do regular approval here.

2023-09-08 08:15 UTC, ind-igo commented on src/Clearinghouse.sol
> +        address ohm_,
You don't need to pass in OHM address. You can grab the OHM address by calling staking.OHM();

I would move this line below line 91, after initializing staking

2023-09-12 07:27 UTC, merged

2023-09-16 00:33 UTC, jkoppel commented on src/Clearinghouse.sol
>          MINTR.burnOhm(address(this), staking.unstake(address(this), totalCollateral - keeperRewards, false, false));
I'm expecting to see `ohm.approve(MINTR, ohm.balanceOf(this));`